### ISSUE TITLE
Sidebar text is clipped short + title appears lower

### ISSUE THREAD

**Issue by allymalecha** [GitMurf/masonry-vanilla#4] opened 2021-02-17 17:10 UTC
Having issues with the sidebar- text appears below the masonry block, and the title doesn't appear until the middle of the page. Not running any other CSS at this time and running the JS listed.
<img width="1397" alt="Screen Shot 2021-02-17 at 10 08 55" src="https://user-images.githubusercontent.com/63561127/108240748-600bdf80-7108-11eb-9b07-bb1f988f6893.png">
<img width="1397" alt="Screen Shot 2021-02-17 at 10 08 48" src="https://user-images.githubusercontent.com/63561127/108240780-669a5700-7108-11eb-9531-e8c7095ded46.png">

**Comment by GitMurf** [comment] 2021-02-19 07:53
@allymalecha I assume this is now working ok after I updated Masonry based on Roam's changes they made to their backend code? I am closing this issue out but let me know if you still are having any issues? Thanks!

**Closed as completed by GitMurf** 2021-02-19 07:53 UTC

**Comment by classicrob** [comment] 2021-02-23 18:30
The issue is still there!
